FORMAT: 1A
HOST: http://api.dailysmarty.com/

# DailySmarty

DailySmarty is a knowledge logging service that allows for users to share what they learn each day. The API allows for 3rd party clients to query posts and securely post to the system via the API.

## List All Posts [/posts]

### Most Recent Posts [GET]

+ Response 200 (application/json)

        [
            {
                "title": "Example of Creating a Service Object in Rails",
                "created_at": "2017-09-06 16:49:11 UTC",
                "content": "<p>Using service object in Rails can be a helpful design pattern to follow for organizing code and separting concerns in your controllers.</p><p>This is a helpful guide for learning how to add service objects in your Rails applications.</p>",
                "url": "http://www.dailysmarty.com/posts/example-of-creating-a-service-object-in-rails",
                "author": "jordan",
                "rating": 100,
                "topics": [
                    {
                        "title": "Development"
                    },
                    {
                        "title": "Ruby on Rails"
                    },
                    {
                        "title": "Design Patterns"
                    }
                ],
                "post_links": [
                    "url": "https://hackernoon.com/service-objects-in-ruby-on-rails-and-you-79ca8a1c946e?gi=518854af8434"
                ]
            }
        ]

### Create a New Post [POST]

You may create your own post using this action. It takes a JSON
object containing a title and pdacontent.

+ Request (application/json)

        {
            "title": "Implementing the Facade Pattern in Rails",
            "content": "The Facade design pattern helps to streamline the setup code in Rails controllers and organize where initial values are stored. This guide provides helpful examples for how this can be implemented in a Rails app.",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }

## Query Posts [/posts?q=rails]

### Search for Posts [GET]

+ Response 200 (application/json)

        [
            {
                "title": "Example of Creating a Service Object in Rails",
                "created_at": "2017-09-06 16:49:11 UTC",
                "content": "<p>Using service object in Rails can be a helpful design pattern to follow for organizing code and separting concerns in your controllers.</p><p>This is a helpful guide for learning how to add service objects in your Rails applications.</p>",
                "url": "http://www.dailysmarty.com/posts/example-of-creating-a-service-object-in-rails",
                "author": "jordan",
                "rating": 100,
                "topics": [
                    {
                        "title": "Development"
                    },
                    {
                        "title": "Ruby on Rails"
                    },
                    {
                        "title": "Design Patterns"
                    }
                ],
                "post_links": [
                    "url": "https://hackernoon.com/service-objects-in-ruby-on-rails-and-you-79ca8a1c946e?gi=518854af8434"
                ]
            }
        ]